version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/work-manage
      - SPRING_DATASOURCE_USERNAME=work-manage
      - SPRING_DATASOURCE_PASSWORD=fd8exxCRcsY5EtNB
    restart: always

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=work-manage
      - POSTGRES_USER=work-manage
      - POSTGRES_PASSWORD=fd8exxCRcsY5EtNB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: